apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: pychat
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository_path }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8888
        env:
        - name: REDIS_PUBSUB
          value: 'true'
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: cm-backend
        volumeMounts:
          - mountPath: "/usr/src/newback/photos"
            name: photo
      volumes:
        - name: photo
          persistentVolumeClaim:
            claimName: pvc-photo

