apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-backend-job
  namespace: pychat
spec:
  template:
    spec:
      containers:
      - name: migrate-backend
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository_path }}:{{ .Values.image.tag }}"
        command: ['/bin/bash', '/usr/src/backend/download_content.sh', "create_django_tables"]
        env:
        - name: BE_DIRECTORY
          value: /usr/src/backend
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: cm-backend
      restartPolicy: Never
  backoffLimit: 4
