apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-backend-job
  namespace: pychat
spec:
  template:
    spec:
      containers:
      - name: migrate-backend
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository_path }}:{{ .Values.image.tag }}"
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: cm-backend
        command: ["yarn",  "migrate"]
      restartPolicy: Never
  backoffLimit: 4
