apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.7.1
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: proxied-tcp-5349
    port: 5349
    targetPort: 5349
    protocol: TCP
  - name: proxied-tcp-3478
    port: 3478
    targetPort: 3478
    protocol: TCP
  - name: proxied-udp-5349
    port: 5349
    targetPort: 5349
    protocol: UDP
  - name: proxied-udp-3478
    port: 3478
    targetPort: 3478
    protocol: UDP
{{ $portGen:= untilStep (.Values.udp_port_range_start | int) ( .Values.udp_port_range_end | int) 1 }} {{ range $index, $port := $portGen }}
  - protocol: UDP
    port: {{ $port }}
    name: coturn-udp-{{ $port }}
    targetPort: {{ $port }}
   {{- end }}
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: NodePort
  externalIPs:
    - "${external_ip}"
