# Generated by Django 2.2.4 on 2020-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191014_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedetails',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
