kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: pvc-redis
   namespace: pychat
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
   storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
   volumeName: pv-redis
