# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-02 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_multiple_images_20170701_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='symbol',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.RunSQL(
            'update chat_message set symbol = (select max(symbol) from chat_image where message_id = chat_message.id)'),
    ]
