apiVersion: batch/v1
kind: Job
metadata:
  name: restore-database-job
  namespace: pychat
spec:
  template:
    spec:
      containers:
      - name: restore-backup
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository_path }}:{{ .Values.image.tag }}"
        command: ["/bin/bash", "/bin/restore.sh"]
        envFrom:
        - secretRef:
            name: secret-backup
        - configMapRef:
            name: cm-backup
        volumeMounts:
          - mountPath: "/src/git/backend/photos"
            name: photo
          - mountPath: "/src/git/"
            name: backup
          - name: git-ssh-key
            mountPath: /src/ssh/id_rsa
            subPath: id_rsa
          - name: git-ssh-key
            mountPath: /src/ssh/id_rsa.pub
            subPath: id_rsa.pub
      restartPolicy: Never
      volumes:
        - name: photo
          persistentVolumeClaim:
            claimName: pvc-photo
        - name: backup
          persistentVolumeClaim:
            claimName: pvc-backup
        - name: git-ssh-key
          secret:
            secretName: secret-backup
  backoffLimit: 4
