// Do not edit this file manually. It was generated with "yarn generate-smileys"
import smileysData from '@/assets/smileys.json';

import {
  PUBLIC_PATH,
} from '@/ts/utils/consts';

export interface SmileVariation {
  alt: string;
  src: string;
}

export interface Smile extends SmileVariation {
  skinVariations?: Record<string, SmileVariation>;
}

export type SmileysStructure = Record<string, Record<string, Smile>>;

Object.values(smileysData).forEach(v => {
  Object.values(v).forEach((s: any) => {
    s.src = `${PUBLIC_PATH ?? ''}/smileys/${s.src}`;
    if (s.skinVariations) {
      Object.values(s.skinVariations).forEach((variation: any) => {
        variation.src = `${PUBLIC_PATH ?? ''}/smileys/${variation.src}`;
      });
    }
  })
});
export const smileys: SmileysStructure = smileysData;
