apiVersion: v1
kind: Service
metadata:
  name: coturn-service
  namespace: pychat
spec:
  selector:
    app: coturn
  ports:
    - protocol: TCP
      name: coturn-main-port-tcp
      port: 5349
      targetPort: 5349
    - protocol: TCP
      port: 3478
      name: coturn-secondary-port-tcp
      targetPort: 3478
    - protocol: UDP
      port: 5349
      name: coturn-main-port-udp
      targetPort: 5349
    - protocol: UDP
      port: 3478
      name: coturn-secondary-port-udp
      targetPort: 3478
    {{ $portGen:= untilStep (.Values.udp_port_range_start | int) ( .Values.udp_port_range_end | int) 1 }} {{ range $index, $port := $portGen }}
    - protocol: UDP
      port: {{ $port }}
      name: coturn-udp-{{ $port }}
      targetPort: {{ $port }}
       {{- end }}

