apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: pychat
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: yobasystems/alpine-mariadb:10.6.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_CHARSET
          value: utf8mb4
        - name: MYSQL_COLLATION
          value: utf8mb4_general_ci
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: config-map
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-data
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: pvc-mariadb
