apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: pychat
spec:
  selector:
    app: postfix
  ports:
    - protocol: TCP
      port: 25
      name: smtp-tls
      targetPort: 25
