apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pychat
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository_path }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
          - mountPath: "/srv/http/photos"
            name: photo
      volumes:
        - name: photo
          persistentVolumeClaim:
            claimName: pvc-photo
