apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: pychat
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: IfNotPresent
        image: deathangel908/pychat-backend
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8888
        env:
        - name: REDIS_PUBSUB
          value: true
        envFrom:
        - secretRef:
            name: secret
        - configMapRef:
            name: config-map
        volumeMounts:
          - mountPath: "/usr/src/newback/photo"
            name: photo
      volumes:
        - name: photo
          persistentVolumeClaim:
            claimName: pvc-photo
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: pychat
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

