apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: pychat
data:
  MYSQL_PORT: '3306'
  MYSQL_DATABASE: pychat
  MYSQL_HOST: mariadb-service
  REDIS_HOST: redis-service
  REDIS_PORT: '6379'
  APPLICATION_PORT: '8888'

