apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pychat
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # change to IfNotPresent for minikube
        imagePullPolicy: Always
        image: deathangel908/pychat-frontend
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
          - mountPath: "/srv/http/photos"
            name: photo
      volumes:
        - name: photo
          persistentVolumeClaim:
            claimName: pvc-photo
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pychat
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

