# helm repo add stable https://charts.helm.sh/stable
# helm install nginx-ingress stable/nginx-ingress --set controller.publishService.enabled=true
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
  name: ingress
  namespace: pychat
spec:
  tls:
  - hosts:
    - pychat.org
    secretName: pychat-tls
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 80
  rules:
  - host: pychat.org
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8888
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8888
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
