apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mariadb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: pvc-mariadb
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
