apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mariadb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: pvc-mariadb
   namespace: pychat
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 5Gi
   storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
   volumeName: pv-mariadb
