apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-photo
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/photo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photo
  namespace: pychat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pv-photo
