udp_port_range_start: $udp_port_range_start
udp_port_range_end: $udp_port_range_end
external_ip: $external_ip
domain_name: $domain_name
static_domain_name: $static_domain_name
docker_domain_name: $docker_domain_name
htpasswd: $htpasswd
