pullPolicy: Always
image:
  repository_path: deathangel908/pychat-backup
  pullPolicy: Always # change to IfNotPresent for minikube
  tag: "latest"

mysql_password: $mysql_password
mysql_user: $mysql_user
mysql_database_name: $mysql_database_name
disk_size: "15Gi"
id_rsa: $id_rsa
id_rsa_pub: $id_rsa_pub
github: $github
